//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CompanyMS.WebReferenceCms {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CmsWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class CmsWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SaveorUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback BindbranchOperationCompleted;
        
        private System.Threading.SendOrPostCallback BindbranchHisOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoademployeebybranchviewOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadempbybranchaddOperationCompleted;
        
        private System.Threading.SendOrPostCallback switchtoupdateviewOperationCompleted;
        
        private System.Threading.SendOrPostCallback SwitchtoupdateaddOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMenuDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateUserOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CmsWebService() {
            this.Url = global::CompanyMS.Properties.Settings.Default.CompanyMS_WebReferenceCms_CmsWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SaveorUpdateCompletedEventHandler SaveorUpdateCompleted;
        
        /// <remarks/>
        public event BindbranchCompletedEventHandler BindbranchCompleted;
        
        /// <remarks/>
        public event BindbranchHisCompletedEventHandler BindbranchHisCompleted;
        
        /// <remarks/>
        public event LoademployeebybranchviewCompletedEventHandler LoademployeebybranchviewCompleted;
        
        /// <remarks/>
        public event LoadempbybranchaddCompletedEventHandler LoadempbybranchaddCompleted;
        
        /// <remarks/>
        public event switchtoupdateviewCompletedEventHandler switchtoupdateviewCompleted;
        
        /// <remarks/>
        public event SwitchtoupdateaddCompletedEventHandler SwitchtoupdateaddCompleted;
        
        /// <remarks/>
        public event GetMenuDataCompletedEventHandler GetMenuDataCompleted;
        
        /// <remarks/>
        public event ValidateUserCompletedEventHandler ValidateUserCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveorUpdate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SaveorUpdate(MasterCBO masterCBO, Employeeinfo[] empList) {
            object[] results = this.Invoke("SaveorUpdate", new object[] {
                        masterCBO,
                        empList});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SaveorUpdateAsync(MasterCBO masterCBO, Employeeinfo[] empList) {
            this.SaveorUpdateAsync(masterCBO, empList, null);
        }
        
        /// <remarks/>
        public void SaveorUpdateAsync(MasterCBO masterCBO, Employeeinfo[] empList, object userState) {
            if ((this.SaveorUpdateOperationCompleted == null)) {
                this.SaveorUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveorUpdateOperationCompleted);
            }
            this.InvokeAsync("SaveorUpdate", new object[] {
                        masterCBO,
                        empList}, this.SaveorUpdateOperationCompleted, userState);
        }
        
        private void OnSaveorUpdateOperationCompleted(object arg) {
            if ((this.SaveorUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveorUpdateCompleted(this, new SaveorUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Bindbranch", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Bindbranch() {
            object[] results = this.Invoke("Bindbranch", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void BindbranchAsync() {
            this.BindbranchAsync(null);
        }
        
        /// <remarks/>
        public void BindbranchAsync(object userState) {
            if ((this.BindbranchOperationCompleted == null)) {
                this.BindbranchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBindbranchOperationCompleted);
            }
            this.InvokeAsync("Bindbranch", new object[0], this.BindbranchOperationCompleted, userState);
        }
        
        private void OnBindbranchOperationCompleted(object arg) {
            if ((this.BindbranchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BindbranchCompleted(this, new BindbranchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BindbranchHis", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable BindbranchHis() {
            object[] results = this.Invoke("BindbranchHis", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void BindbranchHisAsync() {
            this.BindbranchHisAsync(null);
        }
        
        /// <remarks/>
        public void BindbranchHisAsync(object userState) {
            if ((this.BindbranchHisOperationCompleted == null)) {
                this.BindbranchHisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBindbranchHisOperationCompleted);
            }
            this.InvokeAsync("BindbranchHis", new object[0], this.BindbranchHisOperationCompleted, userState);
        }
        
        private void OnBindbranchHisOperationCompleted(object arg) {
            if ((this.BindbranchHisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BindbranchHisCompleted(this, new BindbranchHisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Loademployeebybranchview", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Loademployeebybranchview(string branch_kid) {
            object[] results = this.Invoke("Loademployeebybranchview", new object[] {
                        branch_kid});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void LoademployeebybranchviewAsync(string branch_kid) {
            this.LoademployeebybranchviewAsync(branch_kid, null);
        }
        
        /// <remarks/>
        public void LoademployeebybranchviewAsync(string branch_kid, object userState) {
            if ((this.LoademployeebybranchviewOperationCompleted == null)) {
                this.LoademployeebybranchviewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoademployeebybranchviewOperationCompleted);
            }
            this.InvokeAsync("Loademployeebybranchview", new object[] {
                        branch_kid}, this.LoademployeebybranchviewOperationCompleted, userState);
        }
        
        private void OnLoademployeebybranchviewOperationCompleted(object arg) {
            if ((this.LoademployeebybranchviewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoademployeebybranchviewCompleted(this, new LoademployeebybranchviewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Loadempbybranchadd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Loadempbybranchadd(string branch_kid) {
            object[] results = this.Invoke("Loadempbybranchadd", new object[] {
                        branch_kid});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void LoadempbybranchaddAsync(string branch_kid) {
            this.LoadempbybranchaddAsync(branch_kid, null);
        }
        
        /// <remarks/>
        public void LoadempbybranchaddAsync(string branch_kid, object userState) {
            if ((this.LoadempbybranchaddOperationCompleted == null)) {
                this.LoadempbybranchaddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadempbybranchaddOperationCompleted);
            }
            this.InvokeAsync("Loadempbybranchadd", new object[] {
                        branch_kid}, this.LoadempbybranchaddOperationCompleted, userState);
        }
        
        private void OnLoadempbybranchaddOperationCompleted(object arg) {
            if ((this.LoadempbybranchaddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadempbybranchaddCompleted(this, new LoadempbybranchaddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/switchtoupdateview", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable switchtoupdateview(string branch_kid) {
            object[] results = this.Invoke("switchtoupdateview", new object[] {
                        branch_kid});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void switchtoupdateviewAsync(string branch_kid) {
            this.switchtoupdateviewAsync(branch_kid, null);
        }
        
        /// <remarks/>
        public void switchtoupdateviewAsync(string branch_kid, object userState) {
            if ((this.switchtoupdateviewOperationCompleted == null)) {
                this.switchtoupdateviewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnswitchtoupdateviewOperationCompleted);
            }
            this.InvokeAsync("switchtoupdateview", new object[] {
                        branch_kid}, this.switchtoupdateviewOperationCompleted, userState);
        }
        
        private void OnswitchtoupdateviewOperationCompleted(object arg) {
            if ((this.switchtoupdateviewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.switchtoupdateviewCompleted(this, new switchtoupdateviewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Switchtoupdateadd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Switchtoupdateadd(string branch_kid) {
            object[] results = this.Invoke("Switchtoupdateadd", new object[] {
                        branch_kid});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SwitchtoupdateaddAsync(string branch_kid) {
            this.SwitchtoupdateaddAsync(branch_kid, null);
        }
        
        /// <remarks/>
        public void SwitchtoupdateaddAsync(string branch_kid, object userState) {
            if ((this.SwitchtoupdateaddOperationCompleted == null)) {
                this.SwitchtoupdateaddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSwitchtoupdateaddOperationCompleted);
            }
            this.InvokeAsync("Switchtoupdateadd", new object[] {
                        branch_kid}, this.SwitchtoupdateaddOperationCompleted, userState);
        }
        
        private void OnSwitchtoupdateaddOperationCompleted(object arg) {
            if ((this.SwitchtoupdateaddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SwitchtoupdateaddCompleted(this, new SwitchtoupdateaddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMenuData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetMenuData(int RoleId) {
            object[] results = this.Invoke("GetMenuData", new object[] {
                        RoleId});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetMenuDataAsync(int RoleId) {
            this.GetMenuDataAsync(RoleId, null);
        }
        
        /// <remarks/>
        public void GetMenuDataAsync(int RoleId, object userState) {
            if ((this.GetMenuDataOperationCompleted == null)) {
                this.GetMenuDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMenuDataOperationCompleted);
            }
            this.InvokeAsync("GetMenuData", new object[] {
                        RoleId}, this.GetMenuDataOperationCompleted, userState);
        }
        
        private void OnGetMenuDataOperationCompleted(object arg) {
            if ((this.GetMenuDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMenuDataCompleted(this, new GetMenuDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidateUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ValidateUser(string Username, string Password) {
            object[] results = this.Invoke("ValidateUser", new object[] {
                        Username,
                        Password});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateUserAsync(string Username, string Password) {
            this.ValidateUserAsync(Username, Password, null);
        }
        
        /// <remarks/>
        public void ValidateUserAsync(string Username, string Password, object userState) {
            if ((this.ValidateUserOperationCompleted == null)) {
                this.ValidateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateUserOperationCompleted);
            }
            this.InvokeAsync("ValidateUser", new object[] {
                        Username,
                        Password}, this.ValidateUserOperationCompleted, userState);
        }
        
        private void OnValidateUserOperationCompleted(object arg) {
            if ((this.ValidateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateUserCompleted(this, new ValidateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MasterCBO {
        
        private System.Guid branch_kidField;
        
        private string branch_idField;
        
        private string branch_nameField;
        
        private string branch_departmentField;
        
        private string branch_headField;
        
        private string branchdep_idField;
        
        private int modeField;
        
        /// <remarks/>
        public System.Guid branch_kid {
            get {
                return this.branch_kidField;
            }
            set {
                this.branch_kidField = value;
            }
        }
        
        /// <remarks/>
        public string branch_id {
            get {
                return this.branch_idField;
            }
            set {
                this.branch_idField = value;
            }
        }
        
        /// <remarks/>
        public string branch_name {
            get {
                return this.branch_nameField;
            }
            set {
                this.branch_nameField = value;
            }
        }
        
        /// <remarks/>
        public string branch_department {
            get {
                return this.branch_departmentField;
            }
            set {
                this.branch_departmentField = value;
            }
        }
        
        /// <remarks/>
        public string branch_head {
            get {
                return this.branch_headField;
            }
            set {
                this.branch_headField = value;
            }
        }
        
        /// <remarks/>
        public string branchdep_id {
            get {
                return this.branchdep_idField;
            }
            set {
                this.branchdep_idField = value;
            }
        }
        
        /// <remarks/>
        public int mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Employeeinfo {
        
        private System.Guid emp_idField;
        
        private string emp_nameField;
        
        private string emp_salaryField;
        
        private string emp_emailidField;
        
        private string emp_genderField;
        
        private string emp_branchField;
        
        private string branch_idField;
        
        private string branch_kidField;
        
        private int modeField;
        
        /// <remarks/>
        public System.Guid emp_id {
            get {
                return this.emp_idField;
            }
            set {
                this.emp_idField = value;
            }
        }
        
        /// <remarks/>
        public string emp_name {
            get {
                return this.emp_nameField;
            }
            set {
                this.emp_nameField = value;
            }
        }
        
        /// <remarks/>
        public string emp_salary {
            get {
                return this.emp_salaryField;
            }
            set {
                this.emp_salaryField = value;
            }
        }
        
        /// <remarks/>
        public string emp_emailid {
            get {
                return this.emp_emailidField;
            }
            set {
                this.emp_emailidField = value;
            }
        }
        
        /// <remarks/>
        public string emp_gender {
            get {
                return this.emp_genderField;
            }
            set {
                this.emp_genderField = value;
            }
        }
        
        /// <remarks/>
        public string emp_branch {
            get {
                return this.emp_branchField;
            }
            set {
                this.emp_branchField = value;
            }
        }
        
        /// <remarks/>
        public string branch_id {
            get {
                return this.branch_idField;
            }
            set {
                this.branch_idField = value;
            }
        }
        
        /// <remarks/>
        public string branch_kid {
            get {
                return this.branch_kidField;
            }
            set {
                this.branch_kidField = value;
            }
        }
        
        /// <remarks/>
        public int mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void SaveorUpdateCompletedEventHandler(object sender, SaveorUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveorUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveorUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void BindbranchCompletedEventHandler(object sender, BindbranchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BindbranchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BindbranchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void BindbranchHisCompletedEventHandler(object sender, BindbranchHisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BindbranchHisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BindbranchHisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void LoademployeebybranchviewCompletedEventHandler(object sender, LoademployeebybranchviewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoademployeebybranchviewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoademployeebybranchviewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void LoadempbybranchaddCompletedEventHandler(object sender, LoadempbybranchaddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadempbybranchaddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadempbybranchaddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void switchtoupdateviewCompletedEventHandler(object sender, switchtoupdateviewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class switchtoupdateviewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal switchtoupdateviewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void SwitchtoupdateaddCompletedEventHandler(object sender, SwitchtoupdateaddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SwitchtoupdateaddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SwitchtoupdateaddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetMenuDataCompletedEventHandler(object sender, GetMenuDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMenuDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMenuDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ValidateUserCompletedEventHandler(object sender, ValidateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591